[projects]

  [projects.default]
  contents = [
    "chap1/opensource_scientist",
    "chap1/terminal",
    "chap1/git",
    "chap1/ci",
    "chap2/julia-setup",
    "chap2/julia-why",
    "chap2/julia-type",
    "chap2/release",
    "chap2/performance",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://book.jinguo-group.science"


  # Extra directories to be copied.
  extra_directories = ["assets"]

  # Port used by serve()
  port = 8004

  output_filename = "sci4phys"
