[projects]

  [projects.default]
  contents = [
    "about",
    "julia-setup",
    "lecture1/linux_workflow",
    "appendix",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://book.jinguo-group.science"


  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "sci4phys"
